DROP TABLE IF EXISTS Customer_Product;
DROP TABLE IF EXISTS Order_Product;
DROP TABLE IF EXISTS `Order`;
DROP TABLE IF EXISTS Shipment;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Category;